# Generated by Django 5.2.9 on 2026-01-06 07:53

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='about', verbose_name='image(497x643)px')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='blogs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_main_page', models.BooleanField(default=False, verbose_name='Əsas səhifədə görünsün?')),
            ],
            options={
                'verbose_name': 'Bloglar',
                'verbose_name_plural': 'Bloglar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment')),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Sual',
                'verbose_name_plural': 'Suallar',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Saytın başlığı')),
                ('adress', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('g_adress', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Google Map linki')),
                ('g_adress_iframe', models.TextField(blank=True, null=True, verbose_name='Google Map Iframe linki')),
                ('logo', models.FileField(blank=True, upload_to='general_settings_logo', verbose_name='logo(171x38)')),
                ('mobile_logo', models.FileField(blank=True, help_text='Mobile logo', null=True, upload_to='general_settings_mobile_logo', verbose_name='Mobile logo(172x38)')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='general_settings_favicon', verbose_name='favicon(100x100)')),
                ('footer_logo', models.FileField(blank=True, help_text='Footer logo', null=True, upload_to='general_settings_footer_logo')),
                ('footer_slogan', models.TextField(blank=True, null=True)),
                ('footer_slogan_2', models.TextField(blank=True, null=True)),
                ('copyright_title', models.CharField(blank=True, max_length=100)),
                ('copyright_link', models.TextField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=200, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=200, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='index-slider')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='index-slider-mobile', verbose_name='mobile photo(390x602)px')),
                ('title_small', models.CharField(blank=True, max_length=100, null=True)),
                ('title_big', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Ana səhifə | Slayder',
            },
        ),
        migrations.CreateModel(
            name='IndexVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='index-video')),
                ('iframe_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Ana səhifə | Video',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='choose_section')),
            ],
            options={
                'verbose_name': 'Niyə bizi seçməlisiniz',
                'verbose_name_plural': 'Niyə bizi seçməlisiniz',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='product.generalsettings')),
            ],
            options={
                'verbose_name': 'Nömrə',
                'verbose_name_plural': 'Nömrələr',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product')),
                ('link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='choose_section_punkts')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('whyChooseUs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punkts', to='product.whychooseus')),
            ],
            options={
                'verbose_name': 'Punkt',
                'verbose_name_plural': 'Punktlar',
            },
        ),
    ]
