# Generated by Django 5.0 on 2024-01-06 13:30

from django.db import migrations, models


def create_slugs(apps, schema_editor):
    try:
        from slugify import slugify
    except ImportError:
        # Əgər python-slugify yoxdursa, Django-nun slugify-ni istifadə et
        from django.utils.text import slugify
        
        # Azərbaycan hərflərini əl ilə çevir
        def az_to_latin(text):
            replacements = {
                'ə': 'e', 'Ə': 'E', 'ı': 'i', 'I': 'I',
                'ö': 'o', 'Ö': 'O', 'ü': 'u', 'Ü': 'U',
                'ç': 'c', 'Ç': 'C', 'ğ': 'g', 'Ğ': 'G',
                'ş': 's', 'Ş': 'S'
            }
            for az, lat in replacements.items():
                text = text.replace(az, lat)
            return text
        
        def custom_slugify(text):
            return slugify(az_to_latin(text))
    else:
        def custom_slugify(text):
            return slugify(text, lowercase=True, separator='-')
    
    Product = apps.get_model('product', 'Product')
    Blog = apps.get_model('product', 'Blog')
    
    # Product slug'larını yarad
    used_slugs = set()
    for product in Product.objects.all():
        if not product.slug:
            base_slug = custom_slugify(product.title)
            if not base_slug:  # Əgər title boşdursa
                base_slug = f"product-{product.pk}"
            
            slug = base_slug
            counter = 1
            while slug in used_slugs:
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            used_slugs.add(slug)
            product.slug = slug
            product.save()
    
    # Blog slug'larını yarad
    used_blog_slugs = set()
    for blog in Blog.objects.all():
        if not blog.slug:
            base_slug = custom_slugify(blog.title)
            if not base_slug:  # Əgər title boşdursa
                base_slug = f"blog-{blog.pk}"
            
            slug = base_slug
            counter = 1
            while slug in used_blog_slugs:
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            used_blog_slugs.add(slug)
            blog.slug = slug
            blog.save()


def reverse_slugs(apps, schema_editor):
    # Geri alma funksiyası
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        # Əvvəlcə slug field-ini null=True olaraq əlavə et
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=500, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=500, verbose_name='URL Slug'),
        ),
        # Slug-ları populate et
        migrations.RunPython(create_slugs, reverse_slugs),
        # İndi unique constraint əlavə et
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL Slug'),
        ),
    ]