version: '3'
services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8002:8000
    env_file:
      - ./.env.dev
