# Generated by Django 5.0.2 on 2024-02-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='index-slider')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Ana səhifə | Slayder',
            },
        ),
        migrations.CreateModel(
            name='IndexSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=100, null=True)),
                ('title_big', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='product.indexslider')),
            ],
            options={
                'verbose_name': 'Başlıq',
                'verbose_name_plural': 'Slayder başlıqları',
            },
        ),
    ]
