# Generated by Django 5.0.2 on 2024-02-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_indexslider_description_indexslider_title_big_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='index-slider')),
                ('iframe_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Ana səhifə | Video',
            },
        ),
    ]
