# Generated by Django 5.0.2 on 2024-02-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_indexvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='index-video'),
        ),
    ]
