# Generated by Django 5.0.2 on 2024-02-07 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='choose_section')),
            ],
            options={
                'verbose_name': 'Niyə bizi seçməlisiniz',
                'verbose_name_plural': 'Niyə bizi seçməlisiniz',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='choose_section_punkts')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('whyChooseUs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punkts', to='product.whychooseus')),
            ],
            options={
                'verbose_name': 'Punkt',
                'verbose_name_plural': 'Punktlar',
            },
        ),
    ]
