# Generated by Django 5.0.2 on 2024-02-07 10:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='blogs', verbose_name='photo(370x290)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_main_page', models.BooleanField(default=False, verbose_name='Əsas səhifədə görünsün?')),
            ],
            options={
                'verbose_name': 'Bloglar',
                'verbose_name_plural': 'Bloglar',
            },
        ),
    ]
