# Generated by Django 5.0.2 on 2024-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_contact_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Saytın başlığı')),
                ('adress', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('g_adress', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Google Map linki')),
                ('g_adress_iframe', models.TextField(blank=True, null=True, verbose_name='Google Map Iframe linki')),
                ('logo', models.FileField(blank=True, upload_to='general_settings_logo', verbose_name='logo(171x38)')),
                ('mobile_logo', models.FileField(blank=True, help_text='Mobile logo', null=True, upload_to='general_settings_mobile_logo', verbose_name='Mobile logo(172x38)')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='general_settings_favicon', verbose_name='favicon(100x100)')),
                ('footer_logo', models.FileField(blank=True, help_text='Footer logo', null=True, upload_to='general_settings_footer_logo')),
                ('footer_slogan', models.TextField(blank=True, null=True)),
                ('copyright_title', models.CharField(blank=True, max_length=100)),
                ('copyright_link', models.TextField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=200, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=200, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
