# Generated by Django 5.0.2 on 2024-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_generalsettings_footer_slogan_2_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexslider',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='index-slider-mobile', verbose_name='mobile photo(390x602)px'),
        ),
    ]
