# Generated by Django 5.0 on 2024-01-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('og_title', models.CharField(blank=True, max_length=70, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG Image')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50, verbose_name='Google Tag Manager ID')),
                ('robots_txt', models.TextField(blank=True, verbose_name='robots.txt içeriği')),
            ],
            options={
                'verbose_name': 'SEO Ayarları',
                'verbose_name_plural': 'SEO Ayarları',
            },
        ),
    ]