# Generated by Django 5.0 on 2024-01-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='sitemap_include_blogs',
            field=models.BooleanField(default=True, verbose_name='Blogları sitemap-ə daxil et'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='sitemap_include_products',
            field=models.BooleanField(default=True, verbose_name='Məhsulları sitemap-ə daxil et'),
        ),
    ]